baseURL = "http://retornam.com"
languageCode = "en-us"
title = "Raymond Etornam"
theme ="archie"
Copyright = "retornam.com"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=10 # articles per page


[[menu.main]]
  name = "Archives"
  url = "/posts"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

#[[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 3

[params]
  mode="dark" # light,dark,auto when using archie theme
  useCDN=false # when using archie theme dont use cdn
  description = "retornam.com"


[permalinks]
  posts = "/:year/:month/:title"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

